#!/usr/bin/env python3
"""Generate acceptance test suite for the Markdown-to-HTML converter.

Run as a tool node in the pipeline to create test_converter.py before the
implementer starts. Tests exercise ONLY the public API:
    from markdown_converter import convert

No internal architecture assumptions.
"""

import sys
from pathlib import Path


def get_test_content() -> str:
    lines = []
    a = lines.append

    a('"""Acceptance tests for the Markdown-to-HTML converter.')
    a("")
    a("Tests exercise the public API only: convert(markdown_string) -> html_string.")
    a('Do NOT modify this file. These are your acceptance criteria.')
    a('"""')
    a("import re")
    a("")
    a("from markdown_converter import convert")
    a("")
    a("")
    a("def normalize(html: str) -> str:")
    a('    """Normalize HTML for comparison."""')
    a('    return re.sub(r"\\s+", " ", html.strip())')
    a("")
    a("")
    a("# --- Headings ---")
    a("")
    a("def test_h1():")
    a('    assert normalize(convert("# Hello")) == normalize("<h1>Hello</h1>")')
    a("")
    a("def test_h2():")
    a('    assert normalize(convert("## World")) == normalize("<h2>World</h2>")')
    a("")
    a("def test_h3():")
    a('    assert normalize(convert("### Level 3")) == normalize("<h3>Level 3</h3>")')
    a("")
    a("def test_h4():")
    a('    assert normalize(convert("#### Level 4")) == normalize("<h4>Level 4</h4>")')
    a("")
    a("def test_h5():")
    a('    assert normalize(convert("##### Level 5")) == normalize("<h5>Level 5</h5>")')
    a("")
    a("def test_h6():")
    a('    assert normalize(convert("###### Level 6")) == normalize("<h6>Level 6</h6>")')
    a("")
    a("")
    a("# --- Paragraphs ---")
    a("")
    a("def test_single_paragraph():")
    a('    assert normalize(convert("Hello world")) == normalize("<p>Hello world</p>")')
    a("")
    a("def test_two_paragraphs():")
    a('    md = "First paragraph.\\n\\nSecond paragraph."')
    a("    result = convert(md)")
    a('    assert "<p>First paragraph.</p>" in result')
    a('    assert "<p>Second paragraph.</p>" in result')
    a("")
    a("")
    a("# --- Horizontal rules ---")
    a("")
    a("def test_hr_dashes():")
    a('    assert "<hr" in convert("---").lower()')
    a("")
    a("def test_hr_asterisks():")
    a('    assert "<hr" in convert("***").lower()')
    a("")
    a("def test_hr_underscores():")
    a('    assert "<hr" in convert("___").lower()')
    a("")
    a("")
    a("# --- Inline formatting ---")
    a("")
    a("def test_bold_asterisks():")
    a('    result = convert("This is **bold** text")')
    a('    assert "<strong>bold</strong>" in result')
    a("")
    a("def test_bold_underscores():")
    a('    result = convert("This is __bold__ text")')
    a('    assert "<strong>bold</strong>" in result')
    a("")
    a("def test_italic_asterisk():")
    a('    result = convert("This is *italic* text")')
    a('    assert "<em>italic</em>" in result')
    a("")
    a("def test_italic_underscore():")
    a('    result = convert("This is _italic_ text")')
    a('    assert "<em>italic</em>" in result')
    a("")
    a("def test_inline_code():")
    a('    result = convert("Use the `print()` function")')
    a('    assert "<code>print()</code>" in result')
    a("")
    a("def test_link():")
    a('    result = convert("[Click here](https://example.com)")')
    a("    assert 'href=\"https://example.com\"' in result")
    a('    assert "Click here" in result')
    a("")
    a("def test_image():")
    a('    result = convert("![Alt text](image.png)")')
    a("    assert 'src=\"image.png\"' in result")
    a("    assert 'alt=\"Alt text\"' in result")
    a("")
    a("def test_bold_inside_italic():")
    a('    result = convert("*This is **bold** inside italic*")')
    a('    assert "<em>" in result')
    a('    assert "<strong>bold</strong>" in result')
    a("")
    a("")
    a("# --- Lists ---")
    a("")
    a("def test_unordered_list():")
    a('    md = "- Item 1\\n- Item 2\\n- Item 3"')
    a("    result = convert(md)")
    a('    assert "<ul>" in result')
    a('    assert "<li>" in result')
    a('    assert "Item 1" in result')
    a('    assert "Item 3" in result')
    a("")
    a("def test_ordered_list():")
    a('    md = "1. First\\n2. Second\\n3. Third"')
    a("    result = convert(md)")
    a('    assert "<ol>" in result')
    a('    assert "<li>" in result')
    a('    assert "First" in result')
    a("")
    a("def test_nested_unordered_list():")
    a('    md = "- Top\\n  - Nested\\n    - Deep"')
    a("    result = convert(md)")
    a('    assert result.count("<ul>") >= 2')
    a("")
    a("")
    a("# --- Code blocks ---")
    a("")
    a("def test_fenced_code_block():")
    a("    md = \"```\\nprint('hello')\\n```\"")
    a("    result = convert(md)")
    a('    assert "<pre>" in result or "<code>" in result')
    a('    assert "print(" in result')
    a("")
    a("def test_fenced_code_with_language():")
    a("    md = \"```python\\nprint('hello')\\n```\"")
    a("    result = convert(md)")
    a('    assert "<pre>" in result or "<code>" in result')
    a("")
    a("def test_code_block_preserves_markdown():")
    a("    md = \"```\\n# Not a heading\\n**not bold**\\n```\"")
    a("    result = convert(md)")
    a('    assert "<h1>" not in result')
    a('    assert "<strong>" not in result')
    a("")
    a("")
    a("# --- Blockquotes ---")
    a("")
    a("def test_blockquote():")
    a('    result = convert("> This is quoted")')
    a('    assert "<blockquote>" in result')
    a('    assert "This is quoted" in result')
    a("")
    a("def test_nested_blockquote():")
    a('    md = "> Level 1\\n>> Level 2"')
    a("    result = convert(md)")
    a('    assert result.count("<blockquote>") >= 2')
    a("")
    a("")
    a("# --- Edge cases ---")
    a("")
    a("def test_empty_input():")
    a('    result = convert("")')
    a('    assert result.strip() == ""')
    a("")
    a("def test_whitespace_only():")
    a('    result = convert("   \\n\\n   ")')
    a('    assert result.strip() == ""')
    a("")
    a("def test_consecutive_headings():")
    a('    md = "# One\\n## Two\\n### Three"')
    a("    result = convert(md)")
    a('    assert "<h1>One</h1>" in result')
    a('    assert "<h2>Two</h2>" in result')
    a('    assert "<h3>Three</h3>" in result')
    a("")

    return "\n".join(lines)


def main():
    workspace = Path(".")
    test_file = workspace / "test_converter.py"
    content = get_test_content()
    test_file.write_text(content)
    test_count = content.count("def test_")
    print(f"Wrote {test_file} ({len(content)} bytes, {test_count} tests)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
